// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiCadatroDeFuncionarios.Data;

#nullable disable

namespace WebApiCadatroDeFuncionarios.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20230918150923_Primeira migratiom")]
    partial class Primeiramigratiom
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebApiCadatroDeFuncionarios.Models.FuncionarioModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UltimaAtualização")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("departamento")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("sobrenome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("turno")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("funcionarios");
                });
#pragma warning restore 612, 618
        }
    }
}
